#!/bin/bash

# Ruta absoluta al archivo que lee Waybar
TARGET_FILE="$HOME/.config/waybar/scripts/target.txt"

# Si pasas un argumento, lo guarda. Si no pasas nada, limpia el archivo.
if [ -n "$1" ]; then
  echo "$1" >"$TARGET_FILE"
  echo "Target fijado en: $1"
else
  echo "NONE" >"$TARGET_FILE"
  echo "Target limpiado."
fi
